package master

import (
	"context"
	"encoding/json"
	"fmt"
	"strings"

	"github.com/cloudwego/eino/components/model"
	"github.com/cloudwego/eino/schema"
)

// TaskPlan describes the phases to execute for a penetration testing task,
// generated by the Planner from natural language input.
type TaskPlan struct {
	Target string       `json:"target"`
	Phases []PlanPhase  `json:"phases"`
}

// PlanPhase describes a single phase in the task plan.
type PlanPhase struct {
	Phase  string                 `json:"phase"`
	Tool   string                 `json:"tool"`
	Params map[string]interface{} `json:"params,omitempty"`
}

// Planner turns a user's natural language goal into a structured TaskPlan.
type Planner interface {
	Plan(ctx context.Context, description string) (*TaskPlan, error)
}

// LLMPlanner uses a language model to decompose natural language into a TaskPlan.
type LLMPlanner struct {
	model model.BaseChatModel
}

// NewLLMPlanner creates a planner backed by the given chat model.
func NewLLMPlanner(m model.BaseChatModel) *LLMPlanner {
	return &LLMPlanner{model: m}
}

// Plan sends the user description to the LLM and parses the structured plan.
func (p *LLMPlanner) Plan(ctx context.Context, description string) (*TaskPlan, error) {
	msgs := []*schema.Message{
		schema.SystemMessage(`You are a penetration testing task planner. Your job is to convert a user's natural language goal into a structured task plan in JSON.

Available PTES phases and their default tools:
- reconnaissance → nmap (network discovery)
- vulnerability_scan → nikto (web vulnerability scanner)
- exploitation → custom exploitation (not yet available, skip unless explicitly requested)
- post_exploitation → not yet available, skip unless explicitly requested
- report_generation → auto-generated aggregation, skip unless explicitly requested

Rules:
- Respond ONLY with a JSON object. Do not wrap it in markdown code blocks.
- Infer the target IP, domain, or URL from the user's description.
- Select only the phases that are necessary to fulfill the goal.
- For reconnaissance, nmap params can include scan options like "-sV -sC" or "-p-".
- For vulnerability_scan, nikto params can include the target URL path.

Expected JSON schema:
{
  "target": "192.168.1.100",
  "phases": [
    {"phase": "reconnaissance", "tool": "nmap", "params": {"args": "-sV -sC"}},
    {"phase": "vulnerability_scan", "tool": "nikto", "params": {"target_url": "http://192.168.1.100:80"}}
  ]
}`),
		schema.UserMessage(fmt.Sprintf("Goal: %s", description)),
	}

	resp, err := p.model.Generate(ctx, msgs)
	if err != nil {
		return nil, fmt.Errorf("model generate: %w", err)
	}

	content := strings.TrimSpace(resp.Content)
	content = stripMarkdownFences(content)

	var plan TaskPlan
	if err := json.Unmarshal([]byte(content), &plan); err != nil {
		return nil, fmt.Errorf("parse plan json: %w (raw: %s)", err, content)
	}

	// Validation: at least one phase
	if len(plan.Phases) == 0 {
		return nil, fmt.Errorf("plan contains no phases")
	}

	return &plan, nil
}

// FallbackPlanner returns a hardcoded plan for common patterns when the LLM is unavailable.
type FallbackPlanner struct{}

func (FallbackPlanner) Plan(_ context.Context, description string) (*TaskPlan, error) {
	// Very naive fallback: if description contains an IP-like string, treat it as reconnaissance
	target := extractTarget(description)
	if target == "" {
		return nil, fmt.Errorf("cannot infer target from description: %s", description)
	}
	return &TaskPlan{
		Target: target,
		Phases: []PlanPhase{
			{Phase: "reconnaissance", Tool: "nmap", Params: nil},
			{Phase: "vulnerability_scan", Tool: "nikto", Params: nil},
		},
	}, nil
}

func extractTarget(s string) string {
	// Naive extraction: look for IPv4, IPv6, or domain patterns
	// A robust implementation would use regex; this is a minimal fallback.
	fields := strings.Fields(s)
	for _, f := range fields {
		if strings.Count(f, ".") == 3 {
			return f
		}
		if strings.HasPrefix(f, "http://") || strings.HasPrefix(f, "https://") {
			return f
		}
	}
	return ""
}
